[fuzzer]
max-iterations = 50000
threads = 1

[executor]
executor-type = "command"
command-settings = { command = ["./test_targets/test_target_stdin_check.sh"], input-delivery = "std-in", timeout-ms = 1500 }

[corpus]
corpus-type = "in-memory"
initial-seed-paths = ["seeds/seed1.txt", "seeds/another_seed.bin"]

# TODO:
# [mutator]
# type = "havoc"
# dictionary-path = "./keywords.txt"
