[package]
name = "drifter_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
drifter_core = { path = "../drifter_core" }
anyhow = "1.0"
rand_core = "0.9"
rand_chacha = "0.9"
md5 = "0.7"
toml = "0.8.22"
clap = { version = "4.5", features = ["derive"] }
